# Generated by Django 3.1.7 on 2021-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=15, null=True)),
                ('car_color', models.CharField(max_length=10, null=True)),
                ('car_regNo', models.CharField(max_length=12, null=True)),
                ('car_chassisno', models.TextField(max_length=15)),
                ('car_manfacturing_year', models.DateField()),
            ],
        ),
    ]
